version: '3.8'

services:
  ai-chat-orchestrator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - ai-chat-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass XHiglWjFSMYVudoDfKpFOxsAGrYmYiEu
    volumes:
      - redis_data:/data
    networks:
      - ai-chat-network

volumes:
  redis_data:

networks:
  ai-chat-network:
    driver: bridge